import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import {
  DEFAULT_MAP_APPEARANCE,
  MAP_APPEARANCE_STORAGE_KEY,
  parseMapAppearance,
  readMapAppearanceFromStorage,
  writeMapAppearanceToStorage,
} from '../client/src/lib/mapAppearance.ts';
import { BIOME_STYLES } from '../client/src/lib/biomeStyles.ts';
import { MAP_VISUAL_THEMES } from '../client/src/lib/mapVisualTheme.ts';

assert.equal(parseMapAppearance(null), DEFAULT_MAP_APPEARANCE);
assert.equal(parseMapAppearance('{bad-json'), 'modern');
assert.equal(parseMapAppearance(JSON.stringify({ version: 2, mode: 'immersive' })), 'modern');
assert.equal(parseMapAppearance(JSON.stringify({ version: 1, mode: 'unknown' })), 'modern');
assert.equal(parseMapAppearance(JSON.stringify({ version: 1, mode: 'modern' })), 'modern');
assert.equal(parseMapAppearance(JSON.stringify({ version: 1, mode: 'immersive' })), 'immersive');

const storage = new Map<string, string>();
const adapter = {
  getItem: (key: string) => storage.get(key) ?? null,
  setItem: (key: string, value: string) => storage.set(key, value),
};
writeMapAppearanceToStorage(adapter, 'immersive');
assert.deepEqual(JSON.parse(storage.get(MAP_APPEARANCE_STORAGE_KEY) ?? '{}'), { version: 1, mode: 'immersive' });
assert.equal(readMapAppearanceFromStorage(adapter), 'immersive');
assert.equal(readMapAppearanceFromStorage({ getItem: () => { throw new Error('unavailable'); }, setItem: adapter.setItem }), 'modern');
assert.doesNotThrow(() => writeMapAppearanceToStorage({ getItem: () => null, setItem: () => { throw new Error('unavailable'); } }, 'modern'));
assert.equal(MAP_VISUAL_THEMES.modern.parchmentColor, 0xe8e1d1);
assert.deepEqual(MAP_VISUAL_THEMES.modern.coastlineCore, [0.19, 0.177, 0.153, 0.78]);
assert.deepEqual(MAP_VISUAL_THEMES.immersive.coastlineCore, [0.251, 0.173, 0.129, 0.84]);
assert.equal(BIOME_STYLES.meadows.baseHex, '#91A96B');
assert.equal(BIOME_STYLES.ocean.markHex, '#6F929E');

const workspaceSource = readFileSync(new URL('../client/src/components/MapWorkspace.tsx', import.meta.url), 'utf8');
const mapMenuSource = readFileSync(new URL('../client/src/components/MapMenu.tsx', import.meta.url), 'utf8');
const mapToolbarSource = readFileSync(new URL('../client/src/components/MapToolbar.tsx', import.meta.url), 'utf8');
const coordinateSource = readFileSync(new URL('../client/src/components/CoordinateNavigator.tsx', import.meta.url), 'utf8');
const responsiveOverflowSource = readFileSync(new URL('../client/src/components/ResponsiveOverflowBar.tsx', import.meta.url), 'utf8');
const hudLayoutSource = readFileSync(new URL('../client/src/lib/hudLayout.ts', import.meta.url), 'utf8');
const appearanceSource = readFileSync(new URL('../client/src/lib/mapAppearance.ts', import.meta.url), 'utf8');
const rendererSource = readFileSync(new URL('../client/src/components/map/PixiMapRenderer.ts', import.meta.url), 'utf8');
const canvasSource = readFileSync(new URL('../client/src/components/map/MapCanvas.tsx', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../client/src/styles.css', import.meta.url), 'utf8');
const biomeSource = readFileSync(new URL('../client/src/lib/biomeTextures.ts', import.meta.url), 'utf8');
const parchmentSource = readFileSync(new URL('../client/src/lib/parchmentTextures.ts', import.meta.url), 'utf8');

assert.equal(existsSync(new URL('../client/src/components/AppearanceSelector.tsx', import.meta.url)), false);
assert.match(appearanceSource, /window\.localStorage/);
assert.doesNotMatch(appearanceSource, /sessionStorage/);
assert.match(workspaceSource, /data-ui-mode=\{appearance\}/);
assert.doesNotMatch(workspaceSource, /AppearanceSelector|map-top-hud__right|north-indicator/);
assert.match(workspaceSource, /utility-control__state-mark/);
assert.match(workspaceSource, /appearance === 'modern' && <span className="utility-control__state-mark"/);
assert.match(workspaceSource, /aria-pressed=\{protectEnabled\}/);
assert.match(mapMenuSource, /map-menu__selection/);
assert.match(mapMenuSource, /showSelectionTick &&/);
assert.match(mapMenuSource, /selected \? '✓' : ''/);
assert.match(mapMenuSource, /aria-current=\{selected \? 'true' : undefined\}/);
assert.match(mapMenuSource, /map-menu__map-button/);
assert.match(mapMenuSource, />\s*NEW MAP\s*</);
assert.match(workspaceSource, /showSelectionTick=\{appearance === 'modern'\}/);
assert.ok(workspaceSource.indexOf("id: 'map-library'") < workspaceSource.indexOf("id: 'reset-view'"));
assert.match(mapMenuSource, /className="map-menu__toggle utility-control"/);
assert.match(mapToolbarSource, /toolItem\('pan', 'Pan', 'H'\)/);
assert.match(mapToolbarSource, /toolItem\('biome_brush', 'Biome Brush', 'B'\)/);
assert.match(mapToolbarSource, /toolItem\('eraser', 'Eraser', 'E'\)/);
assert.match(mapToolbarSource, /toolItem\('path', 'Path', 'P'\)/);
assert.match(mapToolbarSource, /toolItem\('marker', 'Marker', 'M'\)/);
assert.match(mapToolbarSource, /toolItem\('select', 'Select', 'V'\)/);
assert.match(mapToolbarSource, /const handleToolClick = \(nextTool: MapTool\) => \{[\s\S]*onToolChange\(nextTool === tool && nextTool !== 'pan' \? 'pan' : nextTool\)/);
assert.match(mapToolbarSource, /handleToolClick\(item\.tool\); closeOverflow\(\)/);
assert.match(mapToolbarSource, /!immersive && hasSelectedPath/);
assert.match(mapToolbarSource, /const hasDeletableSelection = hasSelectedPath \|\| hasSelectedMarker/);
assert.match(mapToolbarSource, /const showsContextualPanel = immersive && \(showsContextualBrushControls \|\| showsContextualPathControls \|\| hasDeletableSelection \|\| showsSelectedMarkerControls\)/);
assert.match(mapToolbarSource, /className="immersive-wood-button immersive-wood-button--danger tool-context-panel__delete"/);
assert.match(mapToolbarSource, />\s*DELETE\s*</);
assert.match(mapToolbarSource, /onClick=\{hasSelectedPath \? onDeleteSelectedPath : onDeleteSelectedMarker\}/);
assert.match(mapToolbarSource, /showShortcut=\{inOverflow\}/);
assert.match(mapToolbarSource, /aria-label=\{shortcutDescription\}/);
assert.match(mapToolbarSource, /title=\{shortcutDescription\}/);
assert.match(mapToolbarSource, /\{label\}\{showShortcut &&/);
assert.match(mapToolbarSource, /showsInlineBrushControls = !immersive && \(tool === 'biome_brush' \|\| tool === 'eraser'\)/);
assert.match(mapToolbarSource, /showsContextualBrushControls = immersive && \(tool === 'biome_brush' \|\| tool === 'eraser'\)/);
assert.match(mapToolbarSource, /showsInlinePathControls = !immersive && tool === 'path'/);
assert.match(mapToolbarSource, /showsContextualPathControls = immersive && tool === 'path'/);
assert.match(mapToolbarSource, /\{showsInlineBrushControls && <BiomeBrushControls/);
assert.match(mapToolbarSource, /\{showsContextualPanel && \([\s\S]*className="map-toolbar tool-context-panel"[\s\S]*showsContextualBrushControls && \([\s\S]*<BrushControls[\s\S]*showBiome=\{tool === 'biome_brush'\}/);
assert.match(mapToolbarSource, /\{showsContextualPanel && \([\s\S]*showsContextualPathControls && \([\s\S]*<PathModePicker pathGeometryType=\{pathGeometryType\}/);
assert.match(mapToolbarSource, /function BiomeBrushControls\([\s\S]*<BiomePicker biome=\{biome\} disabled=\{disabled\} onBiomeChange=\{onBiomeChange\} \/>/);
assert.match(mapToolbarSource, /function BrushControls\([\s\S]*showBiome && <BiomePicker[\s\S]*<BrushSizeControl/);
assert.match(mapToolbarSource, /const PATH_MODE_OPTIONS:[\s\S]*value: 'freehand'[\s\S]*value: 'straight'[\s\S]*value: 'curve'/);
assert.match(mapToolbarSource, /function PathModePicker[\s\S]*pickerId="path-mode-picker"[\s\S]*triggerLabel="Path drawing mode"/);
assert.match(mapToolbarSource, /function ContextualPicker<T extends string>/);
assert.match(workspaceSource, /<MapToolbar[\s\S]*immersive=\{appearance === 'immersive'\}/);
assert.match(workspaceSource, /const enterNeutralPan = useCallback\(\(\) => \{[\s\S]*setTool\('pan'\)[\s\S]*setSelectedMarkerId\(cleared\.selectedMarkerId\)[\s\S]*setSelectedPathId\(null\)/);
assert.match(workspaceSource, /if \(nextTool === 'pan'\) \{[\s\S]*enterNeutralPan\(\);/);
assert.doesNotMatch(mapToolbarSource, /<span>Biome<\/span>/);
assert.doesNotMatch(mapToolbarSource, /Size \{brushWidth\}/);
assert.doesNotMatch(mapToolbarSource, /<select\s+value=\{biome\}/);
assert.match(mapToolbarSource, /aria-label="Brush size"/);
assert.match(mapToolbarSource, /aria-haspopup="listbox"/);
assert.match(mapToolbarSource, /role="listbox"/);
assert.match(mapToolbarSource, /role="option"/);
assert.match(mapToolbarSource, /ArrowDown[\s\S]*ArrowUp[\s\S]*Enter/);
assert.match(mapToolbarSource, /PICKER_VIEWPORT_MARGIN = 12/);
assert.match(mapToolbarSource, /window\.addEventListener\('resize', positionPopup\)/);
assert.doesNotMatch(mapToolbarSource, /ResizeObserver|requestAnimationFrame|setInterval/);
assert.match(mapToolbarSource, /closeForEscape[\s\S]*event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*setOpen\(false\)/);
assert.match(mapMenuSource, /onKeyDown[\s\S]*event\.key === 'Escape'[\s\S]*event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*close\(\)/);
assert.match(mapMenuSource, /document\.addEventListener\('keydown', onKeyDown\)/);
assert.match(coordinateSource, /closeOnEscape[\s\S]*event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*onClose\(\)/);
assert.match(responsiveOverflowSource, /closeOnEscape[\s\S]*event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*setOpen\(false\)/);
assert.match(canvasSource, /event\.key === 'Escape' && !isTypingTarget\(event\.target\)[\s\S]*armedMarkerTypeRef\.current !== null[\s\S]*clearMarkerPlacement\(\);[\s\S]*activePointerGestureRef\.current !== null[\s\S]*cancelActivePointerGesture\(\);[\s\S]*selectedMarkerIdRef\.current !== null \|\| selectedPathIdRef\.current !== null \|\| toolRef\.current !== 'pan'[\s\S]*onToolChange\('pan'\)/);
assert.match(hudLayoutSource, /MEDIUM_UTILITY_IDS = new Set\(\['map-library'/);
assert.match(hudLayoutSource, /NARROW_UTILITY_IDS = new Set\(\['map-library'/);
assert.match(stylesSource, /\.map-top-hud \{[\s\S]*display: flex;[\s\S]*flex-wrap: wrap;[\s\S]*column-gap: 20px;[\s\S]*row-gap: 8px/);
assert.match(stylesSource, /\.map-top-hud__utility \{[\s\S]*flex: 0 0 auto/);
assert.match(stylesSource, /\.map-top-hud__tools \{[\s\S]*flex: 0 0 auto;[\s\S]*margin-left: auto;[\s\S]*justify-content: flex-end/);
assert.doesNotMatch(stylesSource, /map-top-hud\[data-layout-mode='wide'\] \.map-top-hud__tools/);
assert.doesNotMatch(stylesSource, /\.map-top-hud:not\(\[data-layout-mode='wide'\]\)/);
assert.match(coordinateSource, /coordinate-navigator__panel/);
assert.match(coordinateSource, /coordinate-navigator__panel--overlay/);
assert.match(coordinateSource, /anchorRect: DOMRectReadOnly \| null/);
assert.match(coordinateSource, /const VIEWPORT_MARGIN = 12/);
assert.match(coordinateSource, /useLayoutEffect/);
assert.match(coordinateSource, /panel\.getBoundingClientRect\(\)/);
assert.match(coordinateSource, /window\.addEventListener\('resize', positionPanel\)/);
assert.doesNotMatch(coordinateSource, /ResizeObserver|requestAnimationFrame|setInterval/);
assert.match(coordinateSource, /className="immersive-recessed-field"/);
assert.match(coordinateSource, /className="immersive-wood-button"/);
assert.match(coordinateSource, /Cancel/);
assert.match(coordinateSource, />Go</);
assert.match(workspaceSource, /coordinateNavigatorOpen/);
assert.match(workspaceSource, /className="map-popover-layer"/);
assert.match(workspaceSource, /openCoordinateNavigator\(event\.currentTarget\);[\s\S]*closeOverflow\(\)/);
assert.match(stylesSource, /\.map-popover-layer \{[\s\S]*pointer-events: none/);
assert.match(stylesSource, /\.coordinate-navigator__panel--overlay \{[\s\S]*position: fixed;[\s\S]*pointer-events: auto/);
assert.match(stylesSource, /data-ui-mode='immersive'\] \.coordinate-navigator__panel--overlay \{[\s\S]*position: fixed;[\s\S]*width: min\(460px, calc\(100vw - calc\(var\(--immersive-px\) \* 6\)\)\);[\s\S]*max-height: calc\(100dvh - calc\(var\(--immersive-px\) \* 6\)\);[\s\S]*overflow-y: auto/);
assert.match(stylesSource, /coordinate-navigator__panel--overlay \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(stylesSource, /@media \(max-width: 520px\) \{[\s\S]*coordinate-navigator__panel--overlay \{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(stylesSource, /map-menu__form \.immersive-recessed-field,[\s\S]*coordinate-navigator__panel \.immersive-recessed-field/);
assert.match(stylesSource, /coordinate-navigator__panel--overlay \.immersive-recessed-field \{[\s\S]*height: 48px/);
assert.match(stylesSource, /marker-gallery \{[\s\S]*isolation: isolate/);
assert.doesNotMatch(stylesSource, /\.marker-gallery[\s\S]*translate\(-50%, -50%\)/);
assert.match(stylesSource, /coordinate-navigator__panel--overlay::-webkit-scrollbar \{[\s\S]*width: calc\(var\(--immersive-px\) \* 4\)/);
assert.match(stylesSource, /coordinate-navigator__panel--overlay::-webkit-scrollbar-thumb \{[\s\S]*background: var\(--immersive-wood-frame\)[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)/);
assert.match(stylesSource, /coordinate-navigator__panel--overlay \{[\s\S]*scrollbar-color: var\(--immersive-wood-frame\) #d6b778/);
assert.doesNotMatch(stylesSource, /responsive-overflow__dropdown \.coordinate-navigator__panel/);
assert.doesNotMatch(stylesSource, /coordinate-navigator__panel footer button:hover/);
assert.doesNotMatch(stylesSource, /coordinate-navigator__panel footer button:active/);
const panelSizingBlock = stylesSource.slice(stylesSource.lastIndexOf('/* Immersive panel sizing only'));
assert.match(panelSizingBlock, /map-menu__panel \{[\s\S]*width: min\(360px, calc\(100vw - calc\(var\(--immersive-px\) \* 7\)\)\)/);
assert.match(panelSizingBlock, /map-menu__row \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) 56px[\s\S]*min-height: 56px/);
assert.match(panelSizingBlock, /map-menu__map-button,[\s\S]*map-menu__actions-toggle \{[\s\S]*height: 56px/);
assert.match(panelSizingBlock, /map-menu__header > button,[\s\S]*map-menu__actions button \{[\s\S]*height: 52px/);
assert.match(panelSizingBlock, /coordinate-navigator__panel--overlay \{[\s\S]*width: min\(552px, calc\(100vw - calc\(var\(--immersive-px\) \* 6\)\)\)/);
assert.match(panelSizingBlock, /coordinate-navigator__panel--overlay strong \{[\s\S]*font-size: 22px/);
assert.match(panelSizingBlock, /coordinate-navigator__panel--overlay \.immersive-recessed-field \{[\s\S]*height: 56px/);
assert.match(panelSizingBlock, /coordinate-navigator__panel--overlay footer \.immersive-wood-button \{[\s\S]*height: 52px/);
assert.match(panelSizingBlock, /map-menu__form \{[\s\S]*gap: calc\(var\(--immersive-px\) \* 3\)[\s\S]*padding: calc\(var\(--immersive-px\) \* 2\)/);
assert.match(panelSizingBlock, /map-menu__form h2 \{[\s\S]*font-size: 16px/);
assert.match(panelSizingBlock, /map-menu__form \.immersive-recessed-field \{[\s\S]*height: 52px/);
assert.match(panelSizingBlock, /map-menu__form footer button \{[\s\S]*height: 52px[\s\S]*font-size: 14px/);
const hudSizingBlock = stylesSource.slice(stylesSource.lastIndexOf('/* Permanent HUD sizing only'));
assert.match(hudSizingBlock, /--immersive-toolbar-control-height: 52px/);
assert.match(hudSizingBlock, /map-controls \.utility-control,[\s\S]*map-toolbar__tools \.map-toolbar__tool[\s\S]*height: var\(--immersive-toolbar-control-height\)/);
assert.match(hudSizingBlock, /map-controls \.utility-control,[\s\S]*padding-inline: calc\(var\(--immersive-px\) \* 4\)/);
assert.match(hudSizingBlock, /map-controls \.utility-control,[\s\S]*font-size: 18px/);
assert.match(hudSizingBlock, /map-toolbar__tools \.map-toolbar__tool kbd[\s\S]*font-size: 12px/);
assert.doesNotMatch(hudSizingBlock, /transform:\s*scale/);
const popupTypographyBlock = stylesSource.slice(stylesSource.lastIndexOf('/* Popup typography only'));
assert.match(popupTypographyBlock, /map-menu__header,[\s\S]*map-menu__map-button \{[\s\S]*font-size: 20px/);
assert.match(popupTypographyBlock, /map-menu__actions button,[\s\S]*map-menu__form footer button \{[\s\S]*font-size: 18px/);
assert.match(popupTypographyBlock, /map-menu__form h2,[\s\S]*immersive-recessed-field \{[\s\S]*font-size: 20px/);
assert.match(popupTypographyBlock, /coordinate-navigator__panel--overlay strong \{[\s\S]*font-size: 26px/);
assert.match(popupTypographyBlock, /coordinate-navigator__panel--overlay \.coordinate-navigator__hint,[\s\S]*footer \.immersive-wood-button \{[\s\S]*font-size: 20px/);
assert.match(popupTypographyBlock, /coordinate-navigator__panel--overlay \.immersive-recessed-field \{[\s\S]*font-size: 20px/);
assert.doesNotMatch(popupTypographyBlock, /text-shadow|-webkit-text-stroke|font-weight:\s*900/);
const popupTypographyRefinementBlock = stylesSource.slice(stylesSource.lastIndexOf('/* Popup typography refinement'));
assert.match(popupTypographyRefinementBlock, /map-menu__header,[\s\S]*map-menu__map-button \{[\s\S]*font-size: 26px[\s\S]*padding-inline: 19px/);
assert.match(popupTypographyRefinementBlock, /map-menu__actions button,[\s\S]*map-menu__form footer button \{[\s\S]*font-size: 24px/);
assert.match(popupTypographyRefinementBlock, /map-menu__actions button,[\s\S]*map-menu__form footer button \{[\s\S]*padding-inline: 15px/);
assert.match(popupTypographyRefinementBlock, /map-menu__form h2,[\s\S]*immersive-recessed-field \{[\s\S]*font-size: 26px/);
assert.match(popupTypographyRefinementBlock, /map-menu__form \.immersive-recessed-field \{[\s\S]*padding-inline: 19px/);
assert.match(popupTypographyRefinementBlock, /coordinate-navigator__panel--overlay strong \{[\s\S]*font-size: 32px/);
assert.match(popupTypographyRefinementBlock, /coordinate-navigator__panel--overlay \.coordinate-navigator__hint,[\s\S]*footer \.immersive-wood-button \{[\s\S]*font-size: 26px/);
assert.match(popupTypographyRefinementBlock, /coordinate-navigator__panel--overlay footer \.immersive-wood-button \{[\s\S]*padding-inline: 19px/);
assert.match(popupTypographyRefinementBlock, /coordinate-navigator__panel--overlay \.immersive-recessed-field \{[\s\S]*font-size: 26px[\s\S]*padding-inline: 15px/);
assert.doesNotMatch(popupTypographyRefinementBlock, /text-shadow|-webkit-text-stroke|font-weight:\s*900/);
const hudTypographyStart = stylesSource.lastIndexOf('/* Permanent HUD typography only');
const popupTypographyReferenceStart = stylesSource.lastIndexOf('/* Popup controls aligned');
const hudTypographyBlock = stylesSource.slice(hudTypographyStart, popupTypographyReferenceStart);
assert.match(hudTypographyBlock, /map-controls \.responsive-overflow__visible > \.responsive-overflow__item > \.utility-control,[\s\S]*map-toolbar__tools \.responsive-overflow__visible > \.responsive-overflow__item > \.map-toolbar__tool \{[\s\S]*font-size: var\(--immersive-ui-button-font-size\)/);
assert.match(hudTypographyBlock, /map-controls \.responsive-overflow__visible > \.responsive-overflow__item > \.utility-control,[\s\S]*padding-left: 19px[\s\S]*padding-right: 19px/);
assert.doesNotMatch(hudTypographyBlock, /map-toolbar__tools \.responsive-overflow__visible > \.responsive-overflow__item > \.map-toolbar__tool kbd/);
assert.doesNotMatch(hudTypographyBlock, /text-shadow|-webkit-text-stroke|font-weight:\s*900/);
assert.doesNotMatch(hudTypographyBlock, /map-menu__map-button|coordinate-navigator__panel|responsive-overflow__dropdown/);
const coordinateTypographyStart = stylesSource.lastIndexOf('/* Coordinate Navigator typography now');
const popupTypographyReferenceBlock = stylesSource.slice(popupTypographyReferenceStart, coordinateTypographyStart);
assert.match(hudTypographyBlock, /--immersive-ui-button-font-size: 23px/);
assert.match(popupTypographyReferenceBlock, /map-menu__header,[\s\S]*map-menu__actions button,[\s\S]*coordinate-navigator__panel--overlay strong,[\s\S]*footer \.immersive-wood-button \{[\s\S]*font-size: var\(--immersive-ui-button-font-size\)/);
assert.doesNotMatch(popupTypographyReferenceBlock, /coordinate-navigator__hint|coordinate-navigator__panel--overlay label|immersive-recessed-field|map-menu__form/);
const coordinateTypographyBlock = stylesSource.slice(coordinateTypographyStart);
assert.match(coordinateTypographyBlock, /coordinate-navigator__panel--overlay strong,[\s\S]*coordinate-navigator__panel--overlay \.coordinate-navigator__error \{[\s\S]*font-size: var\(--immersive-ui-button-font-size\)/);
assert.match(coordinateTypographyBlock, /coordinate-navigator__panel--overlay \.immersive-recessed-field/);
assert.doesNotMatch(coordinateTypographyBlock, /text-shadow|-webkit-text-stroke|font-weight:\s*900/);
const biomeBrushControlsBlock = stylesSource.slice(stylesSource.lastIndexOf('/* Contextual tool controls'));
assert.match(biomeBrushControlsBlock, /biome-brush-controls \{[\s\S]*gap: var\(--immersive-px\)[\s\S]*margin-left: var\(--immersive-px\)/);
assert.match(biomeBrushControlsBlock, /contextual-picker__trigger \{[\s\S]*height: var\(--immersive-toolbar-control-height\)[\s\S]*font-size: var\(--immersive-ui-button-font-size\)/);
assert.match(biomeBrushControlsBlock, /biome-brush-controls__size \{[\s\S]*height: var\(--immersive-toolbar-control-height\)[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)[\s\S]*box-shadow: none/);
assert.match(biomeBrushControlsBlock, /biome-brush-controls__slider::-webkit-slider-runnable-track \{[\s\S]*border-radius: 0/);
assert.match(biomeBrushControlsBlock, /biome-brush-controls__slider::-webkit-slider-thumb \{[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)[\s\S]*border-radius: 0/);
assert.match(biomeBrushControlsBlock, /biome-brush-controls__slider::-moz-range-track \{[\s\S]*border-radius: 0/);
assert.match(biomeBrushControlsBlock, /biome-brush-controls__slider::-moz-range-thumb \{[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)[\s\S]*border-radius: 0/);
assert.match(biomeBrushControlsBlock, /contextual-picker__popup \{[\s\S]*position: fixed[\s\S]*width: min\(360px, calc\(100vw - calc\(var\(--immersive-px\) \* 6\)\)\)/);
assert.match(biomeBrushControlsBlock, /contextual-picker__popup::before[\s\S]*background: var\(--immersive-wood-outer\)[\s\S]*drop-shadow/);
assert.match(biomeBrushControlsBlock, /contextual-picker__popup::after[\s\S]*background: #d9b978/);
assert.match(biomeBrushControlsBlock, /contextual-picker__list \{[\s\S]*scrollbar-color: var\(--immersive-wood-frame\) #d6b778[\s\S]*scrollbar-width: auto/);
assert.match(biomeBrushControlsBlock, /contextual-picker__list::-webkit-scrollbar-thumb \{[\s\S]*background: var\(--immersive-wood-frame\)[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)[\s\S]*border-radius: 0/);
assert.match(biomeBrushControlsBlock, /contextual-picker__list::-webkit-scrollbar-button \{[\s\S]*display: none/);
assert.match(biomeBrushControlsBlock, /map-top-hud__tools \{[\s\S]*flex-direction: column[\s\S]*align-items: flex-end[\s\S]*gap: var\(--immersive-px\)/);
assert.match(biomeBrushControlsBlock, /map-top-hud__tools > \.map-toolbar \{[\s\S]*width: max-content/);
assert.match(biomeBrushControlsBlock, /map-top-hud__tools > \.tool-context-panel \{[\s\S]*align-self: flex-end/);
assert.match(biomeBrushControlsBlock, /tool-context-panel \.biome-brush-controls \{[\s\S]*margin-left: 0/);
assert.match(biomeBrushControlsBlock, /tool-context-panel > \.contextual-picker \{[\s\S]*align-self: stretch/);
assert.match(biomeBrushControlsBlock, /tool-context-panel \{[\s\S]*gap: var\(--immersive-px\)/);
assert.match(biomeBrushControlsBlock, /tool-context-panel__delete \{[\s\S]*height: var\(--immersive-toolbar-control-height\)[\s\S]*font-size: var\(--immersive-ui-button-font-size\)/);
assert.match(canvasSource, /initialize\(host, appearanceRef\.current\)/);
assert.match(canvasSource, /setAppearance\(appearance\)/);
assert.match(rendererSource, /setBiomeTextureAppearance\(appearance\)/);
assert.match(rendererSource, /uCoastlineFeatherScale/);
assert.doesNotMatch(rendererSource, /uCoastlineQuantization|uCoastlinePhase|updateCoastlineQuantization|physicalCoordinate = floor/);
assert.match(rendererSource, /texture\(uTexture, vTextureCoord\)/);
assert.match(rendererSource, /this\.appearance === 'immersive' \? 2\.5 : 1\.9/);
assert.match(rendererSource, /this\.appearance === 'immersive' \? 0\.4 : 1/);
assert.match(rendererSource, /destroyChildren\(this\.terrainStrokes\)/);
assert.match(rendererSource, /redrawParchment/);
assert.match(rendererSource, /private readonly parchmentSurfaceContainer = new Container\(\)/);
assert.match(rendererSource, /ensureParchmentSurfaceLayers/);
assert.match(rendererSource, /this\.parchmentSurfaceContainer\.alpha = 1/);
assert.match(rendererSource, /this\.parchmentSurfaceContainer\.visible = true/);
assert.match(rendererSource, /this\.parchmentSurfaceContainer\.renderable = true/);
assert.match(rendererSource, /this\.parchmentSurfaceContainer\.addChild\(\.\.\.this\.ensureParchmentSurfaceLayers\(\)\)/);
assert.match(rendererSource, /stage\.addChildAt\(this\.parchmentSurfaceContainer, gridIndex\)/);
assert.match(rendererSource, /textureSpace: 'global'/);
assert.doesNotMatch(rendererSource, /MeshGeometry|Shader|TilingSprite|parchmentSurface\.tilePosition|createParchmentTexture/);
assert.match(parchmentSource, /export const PARCHMENT_TEXTURE_LAYERS/);
assert.match(parchmentSource, /logicalPeriod: 3072/);
assert.match(parchmentSource, /logicalPeriod: 1103/);
assert.match(parchmentSource, /logicalPeriod: 677/);
assert.match(parchmentSource, /seed: 17_381/);
assert.match(parchmentSource, /seed: 52_917/);
assert.match(parchmentSource, /seed: 83_741/);
assert.match(parchmentSource, /Texture\.from/);
assert.match(parchmentSource, /addressMode: 'repeat'/);
assert.match(parchmentSource, /drawWrapped/);
assert.match(parchmentSource, /createImageData/);
assert.match(parchmentSource, /putImageData/);
assert.match(parchmentSource, /valueNoise/);
assert.doesNotMatch(parchmentSource, /createRadialGradient|\.ellipse\(|drawBlob/);
assert.match(parchmentSource, /const alpha = 0\.024 \+ strength \* 0\.04/);
assert.match(parchmentSource, /for \(let index = 0; index < 6000; index \+= 1\)/);
assert.match(parchmentSource, /const width = random\(\) < 0\.86 \? 1 : random\(\) < 0\.97 \? 2 : 3/);
assert.match(parchmentSource, /const length = 2 \+ random\(\) \* 4/);
assert.match(parchmentSource, /cachedTextures/);
assert.match(parchmentSource, /destroyParchmentTextures/);
assert.doesNotMatch(parchmentSource, /Shader|Mesh|TilingSprite|RenderTexture|Math\.random/);
assert.match(rendererSource, /margin = 4 \/ zoom/);
assert.match(rendererSource, /this\.requestStageRender\(\)/);
assert.match(biomeSource, /activeTextureAppearance/);
assert.match(biomeSource, /IMMERSIVE_BIOME_PATTERN_SOURCE_RESOLUTION = 0\.375/);
assert.match(biomeSource, /activeScaleMode/);
assert.match(biomeSource, /scaleMode/);
assert.match(biomeSource, /drawImmersiveBaseVariation/);
assert.match(biomeSource, /const width = random\(\) < 0\.68 \? 3 : random\(\) < 0\.93 \? 4 : 5/);
assert.match(biomeSource, /const height = random\(\) < 0\.2 \? 2 : random\(\) < 0\.92 \? 3 : 4/);
assert.match(biomeSource, /texture\.destroy\(true\)/);
assert.match(stylesSource, /\.map-workspace\[data-ui-mode='immersive'\]/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.utility-control[\s\S]*font-family: ValheimNorse/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.map-menu__panel[\s\S]*clip-path: polygon/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.utility-control[\s\S]*transition: none/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.marker-inspector input[\s\S]*border-width: 2px/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.map-controls[\s\S]*border-width: 3px/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.utility-control[\s\S]*translate\(2px, 2px\)/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.map-menu__panel[\s\S]*clip-path: polygon\(0 6px/);
assert.match(stylesSource, /data-ui-mode='immersive'\][\s\S]*\.marker-gallery__item\[aria-current='true'\][\s\S]*box-shadow:/);
assert.doesNotMatch(stylesSource, /\.map-debug/);
assert.doesNotMatch(workspaceSource, /className="map-debug/);
assert.match(workspaceSource, /const \[debugInfoOpen, setDebugInfoOpen\] = useState\(initialUiPreferences\.debugOpen\)/);
assert.match(workspaceSource, /const \[debugInfoView, setDebugInfoView\] = useState<DebugInfoView>\('readout'\)/);
assert.match(workspaceSource, /const \[debugCoordinateMode, setDebugCoordinateMode\] = useState<DebugCoordinateMode>\(initialUiPreferences\.debugCoordinateMode\)/);
assert.match(workspaceSource, /debugOpen: debugInfoOpen,[\s\S]*debugCoordinateMode,/);
assert.match(workspaceSource, /className="debug-info__button immersive-wood-button"/);
assert.match(workspaceSource, /aria-label="Show debug information"[\s\S]*aria-expanded=\{debugInfoOpen\}/);
assert.ok(workspaceSource.includes("appearance === 'immersive' ? (!debugInfoOpen ? ("));
assert.match(workspaceSource, /className="debug-info__popup"[\s\S]*ZOOM:[\s\S]*debug-info__coordinate-line[\s\S]*<span>X:<\/span>[\s\S]*formatCoordinate\(debugValheim\?\.x\)[\s\S]*debug-info__coordinate-line[\s\S]*<span>Z:<\/span>[\s\S]*formatCoordinate\(debugValheim\?\.z\)/);
assert.match(workspaceSource, /if \(appearance !== 'immersive' && !debugInfoRef\.current\?\.contains\(event\.target as Node\)\)/);
assert.match(workspaceSource, /aria-label="Debug settings"[\s\S]*>\s*\?/);
assert.match(workspaceSource, /aria-label="Close debug information"[\s\S]*onClick=\{closeOrBackDebugInfo\}/);
assert.match(workspaceSource, /aria-label="Back to debug information"[\s\S]*onClick=\{closeOrBackDebugInfo\}/);
assert.match(workspaceSource, /debug-info__coordinate-line[\s\S]*<span>X:<\/span>[\s\S]*<span>\{formatCoordinate/);
assert.match(workspaceSource, /debug-info__coordinate-line[\s\S]*<span>Z:<\/span>[\s\S]*<span>\{formatCoordinate/);
assert.match(workspaceSource, /debug-info__symbol" aria-hidden="true">\?<\/span>/);
assert.match(workspaceSource, /role="radiogroup" aria-label="Coordinate source"[\s\S]*role="radio"[\s\S]*aria-checked=\{debugCoordinateMode === mode\}/);
assert.match(workspaceSource, /const centreValheim = mapToValheimCoordinates\(mapSession\.camera\.cameraX, mapSession\.camera\.cameraY\)/);
assert.match(workspaceSource, /const debugValheim = debugCoordinateMode === 'cursor' \? cursorValheim : centreValheim/);
assert.match(workspaceSource, /closeOnEscape[\s\S]*debugInfoView === 'settings'[\s\S]*setDebugInfoView\('readout'\)[\s\S]*closeDebugInfo\(\)/);
assert.match(stylesSource, /\.map-workspace \{[\s\S]*--hud-edge-inset: 14px/);
assert.match(stylesSource, /\.map-top-hud \{[\s\S]*top: var\(--hud-edge-inset\)[\s\S]*left: var\(--hud-edge-inset\)/);
assert.match(stylesSource, /\.debug-info \{[\s\S]*bottom: var\(--hud-edge-inset\)[\s\S]*left: var\(--hud-edge-inset\)/);
assert.match(stylesSource, /debug-info__popup \{[\s\S]*font-size: calc\(var\(--immersive-ui-button-font-size\) - 3px\)/);
assert.match(stylesSource, /data-ui-mode='immersive'\] \.debug-info__popup[\s\S]*clip-path: polygon/);
assert.match(stylesSource, /data-ui-mode='immersive'\] \.debug-info__popup::before[\s\S]*drop-shadow/);
assert.match(stylesSource, /data-ui-mode='immersive'\] \.debug-info__symbol[\s\S]*box-sizing: border-box[\s\S]*width: calc\(var\(--immersive-px\) \* 5\)[\s\S]*font-family: ValheimNorse, Georgia, serif[\s\S]*font-size: calc\(var\(--immersive-ui-button-font-size\) \+ 2px\)[\s\S]*border: 0[\s\S]*border-radius: 0/);
assert.match(stylesSource, /debug-info__action[\s\S]*width: calc\(var\(--immersive-px\) \* 8\)[\s\S]*height: calc\(var\(--immersive-px\) \* 8\)/);
assert.match(stylesSource, /\.debug-info__zoom-line \{[\s\S]*align-items: center/);
assert.match(stylesSource, /data-ui-mode='immersive'\] \.debug-info__coordinate-line[\s\S]*gap: var\(--immersive-px\)/);
assert.match(stylesSource, /\.map-workspace\[data-ui-mode='immersive'\] \{[\s\S]*font-family: ValheimNorse, Georgia, serif/);
assert.match(mapMenuSource, /map-menu__map-button immersive-wood-button/);
assert.match(mapMenuSource, /map-menu__actions-toggle immersive-wood-button/);
assert.match(mapMenuSource, /className="immersive-wood-button"/);
assert.match(mapMenuSource, /immersive-wood-button--danger/);
assert.match(mapMenuSource, /className="immersive-recessed-field"/);
assert.match(mapMenuSource, /aria-current={selected \? 'true' : undefined}/);
assert.match(stylesSource, /map-menu__row \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) 48px/);
assert.match(stylesSource, /map-workspace\[data-ui-mode='immersive'\] \.map-menu__list \{[\s\S]*padding: calc\(var\(--immersive-px\) \* 3\)/);
assert.match(stylesSource, /map-menu__list \{[\s\S]*scrollbar-gutter: stable/);
assert.match(stylesSource, /map-menu__list::-webkit-scrollbar \{[\s\S]*width: calc\(var\(--immersive-px\) \* 4\)/);
assert.match(stylesSource, /map-menu__list::-webkit-scrollbar-track \{[\s\S]*background: #d6b778[\s\S]*border-radius: 0/);
assert.match(stylesSource, /map-menu__list::-webkit-scrollbar-thumb \{[\s\S]*background: var\(--immersive-wood-frame\)[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)[\s\S]*border-radius: 0/);
assert.match(stylesSource, /map-menu__list::-webkit-scrollbar-button \{[\s\S]*display: none/);
assert.match(stylesSource, /map-menu__list \{[\s\S]*scrollbar-color: var\(--immersive-wood-frame\) #d6b778[\s\S]*scrollbar-width: auto/);
assert.match(stylesSource, /--immersive-px:\s*4px/);
assert.match(stylesSource, /--immersive-panel-step:\s*calc\(var\(--immersive-px\) \* 2\)/);
assert.match(stylesSource, /clip-path:\s*polygon\([\s\S]*var\(--immersive-panel-step\)/);
assert.match(stylesSource, /filter:\s*drop-shadow\([\s\S]*var\(--immersive-deep-ink\)/);
assert.match(stylesSource, /transform:\s*translate\(var\(--immersive-px\), var\(--immersive-px\)\)/);
assert.match(stylesSource, /map-toolbar__size input\[type='range'\][\s\S]*::-webkit-slider-thumb/);
assert.doesNotMatch(stylesSource, /\.map-menu__row--selected\s*\{\s*border-left-color/);
assert.doesNotMatch(stylesSource, /\.map-menu__row\s*\{\s*border-(?:left|bottom)/);
assert.match(stylesSource, /map-toolbar__tools \.responsive-overflow__visible[\s\S]*gap: 4px/);
assert.match(stylesSource, /\.map-workspace\[data-ui-mode='immersive'\] \.map-controls/);
assert.match(stylesSource, /--immersive-control-height:\s*44px/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*padding: 0 8px/);
assert.match(stylesSource, /map-controls \.responsive-overflow__toggle[\s\S]*min-width: calc\(var\(--immersive-px\) \* 7\)/);
assert.match(stylesSource, /map-controls \.responsive-overflow__visible[\s\S]*gap: 4px/);
assert.match(stylesSource, /map-toolbar__tools \.map-toolbar__tool[\s\S]*clip-path: none/);
assert.match(stylesSource, /map-controls \.responsive-overflow__visible > \.responsive-overflow__item:not\(:last-child\)[\s\S]*border-right-width: 2px/);
assert.match(stylesSource, /map-toolbar__tools \.responsive-overflow__visible > \.responsive-overflow__item:not\(:last-child\)[\s\S]*border-right-width: 2px/);
assert.match(stylesSource, /map-controls \.utility-control:active[\s\S]*transform: none/);
assert.match(stylesSource, /Solid silhouette frames/);
assert.match(stylesSource, /map-controls,\n\.map-workspace\[data-ui-mode='immersive'\] \.map-toolbar[\s\S]*border: 0[\s\S]*clip-path: none/);
assert.match(stylesSource, /map-workspace\[data-ui-mode='immersive'\] \.map-controls::before[\s\S]*background: var\(--immersive-deep-ink\)[\s\S]*clip-path: polygon/);
assert.match(stylesSource, /map-workspace\[data-ui-mode='immersive'\] \.map-controls::after[\s\S]*background: #d6b778[\s\S]*clip-path: polygon/);
assert.match(stylesSource, /map-workspace\[data-ui-mode='immersive'\] \.map-controls::before[\s\S]*filter: drop-shadow/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*border: 0[\s\S]*box-shadow: inset 0 2px/);
assert.match(stylesSource, /--immersive-wood-outer:\s*#3b2418/);
assert.match(stylesSource, /--immersive-wood-face:\s*#b96f35/);
assert.match(stylesSource, /--immersive-wood-selected:\s*#9e4f27/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*background-color: var\(--immersive-wood-face\)/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*background-image:[\s\S]*linear-gradient\(90deg/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*box-shadow: inset 0 4px/);
assert.match(stylesSource, /map-toolbar__tool--active,[\s\S]*background-color: var\(--immersive-wood-selected\)[\s\S]*box-shadow: inset 0 2px/);
assert.match(stylesSource, /responsive-overflow__dropdown::after,[\s\S]*background: #d9b978/);
assert.match(stylesSource, /--immersive-toolbar-control-height:\s*44px/);
assert.match(stylesSource, /map-controls \.responsive-overflow,[\s\S]*map-toolbar__tools \.responsive-overflow,[\s\S]*gap: 0/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*height: var\(--immersive-toolbar-control-height\)/);
assert.match(stylesSource, /map-controls \.responsive-overflow__visible > \.responsive-overflow__item:not\(:first-child\)[\s\S]*border-left: 2px/);
assert.match(stylesSource, /map-controls \.responsive-overflow,[\s\S]*filter: drop-shadow\(0 var\(--immersive-px\)/);
assert.match(stylesSource, /map-controls::before,[\s\S]*map-controls::after,[\s\S]*display: none/);
assert.match(stylesSource, /map-controls \.responsive-overflow,[\s\S]*map-toolbar__tools \.responsive-overflow[\s\S]*gap: 4px/);
assert.match(stylesSource, /map-controls \.utility-control,[\s\S]*2px 2px 0 var\(--immersive-deep-ink\)/);
assert.doesNotMatch(stylesSource, /data-ui-mode='immersive'[^{}]*\.map-controls[^{}]*\.utility-control:(?:first|last)-child/);

// The final geometry block is authoritative for connected HUD state. Older
// historical rules remain in this stylesheet for compatibility, so verify the
// last block rather than mistaking an overridden declaration for live chrome.
const finalGeometryBlock = stylesSource.slice(stylesSource.lastIndexOf('/* Final state-geometry normalization'));
const dangerMatch = finalGeometryBlock.match(/\.immersive-wood-button--danger\s*\{([^}]*)\}/);
assert.ok(dangerMatch, 'Immersive danger-button modifier is present');
const dangerBlock = dangerMatch[1];
assert.match(finalGeometryBlock, /--immersive-toolbar-control-height/);
assert.match(finalGeometryBlock, /height: var\(--immersive-toolbar-control-height\)/);
assert.match(finalGeometryBlock, /min-height: var\(--immersive-toolbar-control-height\)/);
assert.match(finalGeometryBlock, /max-height: var\(--immersive-toolbar-control-height\)/);
assert.match(finalGeometryBlock, /align-self: stretch/);
assert.match(finalGeometryBlock, /\.map-toolbar__tool--active[\s\S]*transform: none/);
assert.match(finalGeometryBlock, /\.utility-control\[aria-pressed='true'\][\s\S]*transform: none/);
assert.match(finalGeometryBlock, /responsive-overflow__item \{[\s\S]*border-right: 0/);
assert.match(finalGeometryBlock, /--immersive-slot-rim: var\(--immersive-px\)/);
assert.match(finalGeometryBlock, /--immersive-toolbar-rim:\s*#684025/);
assert.match(finalGeometryBlock, /--immersive-slot-rim-color: var\(--immersive-toolbar-rim\)/);
assert.match(finalGeometryBlock, /--immersive-slot-bevel-depth: calc\(var\(--immersive-px\) \* 2\)/);
assert.match(finalGeometryBlock, /--immersive-slot-highlight-x: 0px/);
assert.match(finalGeometryBlock, /--immersive-slot-highlight-y: var\(--immersive-px\)/);
assert.match(finalGeometryBlock, /\.immersive-wood-button \{[\s\S]*--immersive-slot-rim: var\(--immersive-px\)[\s\S]*--immersive-slot-highlight-x: var\(--immersive-px\)/);
assert.match(finalGeometryBlock, /\.immersive-wood-button::before/);
assert.match(finalGeometryBlock, /\.immersive-wood-button::after[\s\S]*left \/ var\(--immersive-slot-rim\) 100%/);
assert.match(finalGeometryBlock, /\.immersive-wood-button \{[\s\S]*inset 0 calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 var\(--immersive-wood-shadow\)[\s\S]*inset calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 0 var\(--immersive-wood-shadow\)/);
assert.match(finalGeometryBlock, /\.immersive-wood-button:active \{[\s\S]*background-image: none;[\s\S]*inset 0 calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 var\(--immersive-wood-highlight\)[\s\S]*inset calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 0 var\(--immersive-wood-highlight\)/);
assert.match(finalGeometryBlock, /\.immersive-wood-button\[aria-current='true'\]::before,[\s\S]*linear-gradient\(var\(--immersive-toolbar-rim\), var\(--immersive-toolbar-rim\)\)/);
assert.match(finalGeometryBlock, /\.immersive-wood-button\[aria-current='true'\],[\s\S]*background-image: none;[\s\S]*var\(--immersive-wood-highlight\)/);
assert.match(finalGeometryBlock, /\.immersive-wood-button:focus-visible \{[\s\S]*outline: var\(--immersive-px\) solid var\(--immersive-wood-highlight\)/);
assert.doesNotMatch(finalGeometryBlock, /map-menu__map-button::before|map-menu__map-button::after/);
assert.match(finalGeometryBlock, /\.immersive-wood-button \{[\s\S]*border: 0[\s\S]*clip-path: none/);
assert.match(finalGeometryBlock, /\.map-menu__row \{[\s\S]*border: 0[\s\S]*box-shadow: none[\s\S]*background: transparent/);
assert.match(finalGeometryBlock, /\.map-menu__actions \{[\s\S]*border: 0[\s\S]*box-shadow: none[\s\S]*background: transparent/);
assert.match(finalGeometryBlock, /\.immersive-wood-button--danger \{[\s\S]*background-color: var\(--immersive-wood-selected\)/);
assert.doesNotMatch(finalGeometryBlock, /\.map-menu__delete\s*\{/);
assert.doesNotMatch(finalGeometryBlock, /map-menu__actions-toggle::before|map-menu__actions-toggle::after/);
assert.doesNotMatch(dangerBlock, /background-image|box-shadow|transform/);
assert.doesNotMatch(stylesSource, /data-ui-mode='immersive'\] \.map-menu button/);
assert.match(finalGeometryBlock, /\.map-menu__form \.immersive-recessed-field,[\s\S]*\.coordinate-navigator__panel \.immersive-recessed-field \{[\s\S]*border: var\(--immersive-px\) solid var\(--immersive-toolbar-rim\)[\s\S]*inset 0 var\(--immersive-px\) 0 var\(--immersive-wood-shadow\)[\s\S]*inset 0 calc\(var\(--immersive-px\) \* -1\) 0 var\(--immersive-wood-highlight\)/);
assert.match(finalGeometryBlock, /first-child > button,[\s\S]*--immersive-slot-highlight-x: var\(--immersive-px\)/);
assert.match(finalGeometryBlock, /background-position:[\s\S]*var\(--immersive-slot-highlight-x\) var\(--immersive-slot-highlight-y\),[\s\S]*var\(--immersive-slot-highlight-x\) var\(--immersive-slot-highlight-y\)/);
assert.match(finalGeometryBlock, /background-size:[\s\S]*var\(--immersive-px\),[\s\S]*var\(--immersive-px\) calc\(100% - var\(--immersive-slot-highlight-y\) - var\(--immersive-slot-rim\)\)/);
assert.match(finalGeometryBlock, /utility-control\[aria-pressed='true'\]::before,[\s\S]*linear-gradient\(var\(--immersive-toolbar-rim\), var\(--immersive-toolbar-rim\)\),[\s\S]*linear-gradient\(var\(--immersive-toolbar-rim\), var\(--immersive-toolbar-rim\)\)/);
assert.match(finalGeometryBlock, /map-toolbar__tool--active::before,[\s\S]*linear-gradient\(var\(--immersive-toolbar-rim\), var\(--immersive-toolbar-rim\)\),[\s\S]*linear-gradient\(var\(--immersive-toolbar-rim\), var\(--immersive-toolbar-rim\)\)/);
assert.match(finalGeometryBlock, /box-shadow: inset 0 calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 var\(--immersive-wood-shadow\)/);
assert.match(finalGeometryBlock, /box-shadow: inset 0 calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 var\(--immersive-wood-highlight\)/);
assert.match(finalGeometryBlock, /background-image: none;[\s\S]*box-shadow: inset 0 calc\(var\(--immersive-slot-bevel-depth\) \* -1\) 0 var\(--immersive-wood-highlight\)/);
assert.match(finalGeometryBlock, /map-controls \.utility-control,[\s\S]*padding-inline: 12px/);
assert.match(finalGeometryBlock, /::after[\s\S]*linear-gradient\(var\(--immersive-slot-rim-color\), var\(--immersive-slot-rim-color\)\) top \/ 100% var\(--immersive-slot-rim\)/);
assert.match(finalGeometryBlock, /linear-gradient\(var\(--immersive-slot-rim-color\), var\(--immersive-slot-rim-color\)\) bottom \/ 100% var\(--immersive-slot-rim\)/);
assert.match(finalGeometryBlock, /linear-gradient\(var\(--immersive-slot-rim-color\), var\(--immersive-slot-rim-color\)\) right \/ var\(--immersive-slot-rim\) 100%/);
assert.match(finalGeometryBlock, /first-child > button::after[\s\S]*linear-gradient\(var\(--immersive-slot-rim-color\), var\(--immersive-slot-rim-color\)\) left \/ var\(--immersive-slot-rim\) 100%/);
assert.match(finalGeometryBlock, /border: 0/);
assert.doesNotMatch(finalGeometryBlock, /:last-child/);
assert.doesNotMatch(finalGeometryBlock, /slot-right-edge|top-right 4x4|corner owner/);

console.log('Appearance persistence and theme wiring verification passed');
